    # BCIIV2A
    configs = {
        'class_num': 4,
        'channelNum': 22,
        'width': 300,
        'time':1000
    }
    # BCIIV2B
    configs = {
        'class_num': 2,
        'channelNum': 3,
        'width': 300,
        'time': 1000
    }
    # PhysioNet
    configs = {
        'class_num': 2,
        'channelNum': 64,
        'width': 300,
        'time': 640
    }
